# Copyright 2013-2019 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
---
config:
  build_stage: /spack/stage
  source_cache: /spack/cache
  install_tree: /spack/sw
  module_roots:
    tcl: /spack/modules
modules:
  tcl:
    naming_scheme: '{name}/{version}-{compiler.name}{compiler.version}'
    hash_length: 4
    all:
      conflict:
        - '{name}'
